import Head from 'next/head'


import Container from '../../components/UI/Container/container'
import Layout from '../../components/UI/layout/layout'
import ViewProfile from '../../components/User/profile/view'

export default function Home() {
  return (
    <>
      <Head>
          <title>Dev-Girl</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <Layout>
            <ViewProfile/>
        </Layout>
      </Container>
    
    </>
  )
}