import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'


import Container from '../components/UI/Container/container.js'
import Layout from '../components/UI/Layout/layout.js'

export default function Home() {
  return (
    <>
      <Head>
          <title>Dev-Girl</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <Layout>
          
        </Layout>
      </Container>
    
    </>
  )
}
