import * as style from './sign-in-style.jsx'

import Head from 'next/head'

import Link from 'next/link'
import Form from '../../components/User/sign-in/form.js'
import Auth from '../../components/User/auth/auth.js'
import Container from '../../components/UI/Container/container.js'

export default function Login(){
    return(
        <>
            <Head>
                <title>Entrar</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
            <Container>
                <style.modal >
                    <Auth/>
                    <style.line></style.line>
                    <Form/>
                    <Link href='./sign-up'>
                        <a>
                            <style.p>Cadastrar</style.p>
                        </a>
                    </Link>
                </style.modal>
                
            </Container>
        </>
    )
}